use sqlx::{AnyPool, FromRow};

use crate::{error::OrmError, query_builder::QueryBuilder};

/// Active Record trait.  Implemented automatically by `#[model]`.
///
/// Default CRUD methods are provided here; `save()` and `delete()` are
/// generated by the `#[model]` macro because they need access to field
/// names and types at compile time.
pub trait Model: Sized + Send + Sync + Unpin + for<'r> FromRow<'r, sqlx::any::AnyRow> {
    /// Database table name (snake_case plural).
    fn table_name() -> &'static str;

    /// Primary key column name (default: `"id"`).
    fn primary_key() -> &'static str {
        "id"
    }

    // ── READ ─────────────────────────────────────────────────────────────────

    /// Find a record by its primary key.
    async fn find(id: i64, pool: &AnyPool) -> Result<Option<Self>, OrmError> {
        let sql = format!(
            "SELECT * FROM {} WHERE {} = ?",
            Self::table_name(),
            Self::primary_key(),
        );
        let row = sqlx::query_as::<sqlx::Any, Self>(&sql)
            .bind(id)
            .fetch_optional(pool)
            .await?;
        Ok(row)
    }

    /// Return every row in the table.
    async fn all(pool: &AnyPool) -> Result<Vec<Self>, OrmError> {
        let sql = format!("SELECT * FROM {}", Self::table_name());
        let rows = sqlx::query_as::<sqlx::Any, Self>(&sql)
            .fetch_all(pool)
            .await?;
        Ok(rows)
    }

    /// Total number of rows.
    async fn count(pool: &AnyPool) -> Result<i64, OrmError> {
        let sql = format!("SELECT COUNT(*) FROM {}", Self::table_name());
        let (n,): (i64,) = sqlx::query_as::<sqlx::Any, (i64,)>(&sql)
            .fetch_one(pool)
            .await?;
        Ok(n)
    }

    /// Check whether at least one row matches the WHERE clause.
    async fn exists(condition: &str, pool: &AnyPool) -> Result<bool, OrmError> {
        let sql = format!(
            "SELECT COUNT(*) FROM {} WHERE {}",
            Self::table_name(),
            condition,
        );
        let (n,): (i64,) = sqlx::query_as::<sqlx::Any, (i64,)>(&sql)
            .fetch_one(pool)
            .await?;
        Ok(n > 0)
    }

    // ── QUERY BUILDER ────────────────────────────────────────────────────────

    /// Start a fluent query against this table.
    ///
    /// ```ignore
    /// User::query()
    ///     .where_eq("email", "alice@example.com")
    ///     .order_by("created_at", "DESC")
    ///     .limit(10)
    ///     .all(&pool)
    ///     .await?
    /// ```
    fn query() -> QueryBuilder<Self> {
        QueryBuilder::new(Self::table_name())
    }
}
